#!/usr/bin/python3

a = []
file = open("tests/test00", "r")
a.append([int(line) for line in file])
x = a[0]
print(x)

for j in range(len(x)):
    y = []
    for i in range(1, x[j] + 1):
        if x[j] % i == 0:
            y.append((i, x[j] / i))
    p = y[1][1]
    q = y[1][0]

    print("{:.0f}={:.0f}*{:d}".format(p * q, p, q))
