#!/usr/bin/python3

a = []
file = open("tests/test00", "r")
a.append([float(line) for line in file])
x = a[0]

for j in range(len(x)):
    y = []
    for i, val  in enumerate(x):
        #i += 1
        try:
            x[j] % i
        except ZeroDivisionError:
            i += 1
        if x[j] % i == 0:
            y.append((i, x[j] / i))
        i += 1
    p = y[1][1]
    q = y[1][0]

    print("{:.0f}={:.0f}*{:d}".format(p * q, p, q))
